### ISSUE TITLE
--power argument seems to be ignored 

### ISSUE THREAD

**Issue by dkbnz** [yurinnick/folding-at-home-docker#17]
While trying to set the power level using the environment var POWER,
It seems to be ignored.

My compose file:
```
version: "2.4"

networks:
  proxy:
    external: true

services:

  folding-at-home:
    image: yurinnick/folding-at-home
    container_name: folding-at-home
    networks:
      - proxy
    command: ["--allow=0/0", "--web-allow=0/0"] # Allow connections from non-localhost ip addresses
    volumes:
      - ~/homelab_data/folding:/opt/fahclient/work
    environment:
      - USER=plateofash
      - TEAM=0
      - ENABLE_GPU=false
      - ENABLE_SMP=true
      - POWER=light
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.folding-at-home.entrypoints=http"
      - "traefik.http.routers.folding-at-home.rule=Host(`folding.${DOMAIN}`)"
      - "traefik.http.services.folding-at-home.loadbalancer.server.port=7396"
```

However, after starting and analysing the logs, I see the power passed to FAHClient is "full"

```
05:01:54:       Args: --user=plateofash --team=0 --passkey= --gpu=false --smp=true
05:01:54:             --power=full --gui-enabled=false --allow=0/0 --web-allow=0/0
```
From within the container, the env variable is set.

```
folding@d40eac954e68:/opt/fahclient$ echo $POWER 
light
```

I've also tried with and without quotations.

If others are having this issue, the built in docker resource limitations work perfectly and is what I have resorted to.
